apiVersion: v1
kind: Service
metadata:
  labels: {{ include "daemonjob-operator.labels" . | nindent 4 }}
  name: {{ include "daemonjob-operator.name" . }}-controller-manager-metrics-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector: {{ include "daemonjob-operator.labels" . | nindent 4 }}