
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs/finalizers
  verbs:
  - update
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs/status
  verbs:
  - get
  - patch
  - update
