apiVersion: daemon.justk8s.com/v1alpha1
kind: DaemonJob
metadata:
  name: daemonjob-sample
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: busybox
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
