apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "daemonjob-operator.name" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "daemonjob-operator.name" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "daemonjob-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}