# permissions for end users to edit daemonjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemonjob-editor-role
rules:
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs/status
  verbs:
  - get
