# permissions for end users to view daemonjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemonjob-viewer-role
rules:
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - daemon.justk8s.com
  resources:
  - daemonjobs/status
  verbs:
  - get
