apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "daemonjob-operator.name" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "daemonjob-operator.name" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "daemonjob-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}