{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "daemonjob-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}